### PR TITLE
Remove Etrigan and add a new web-ui

### PR DESCRIPTION
**Pull request by simonmicro**
- [x] remove etrigan
  - [x]  remove etrigan gui -> pykms_GuiBase
  - [x]     remove requirements from requirements.txt
  - [x]     remove config options for etrigan
  - [x]     update docs
- [x] remove sqliteweb support
  - [x]     from docker
  - [x]     port 8080? reuse and / or remove from docs
- [x] change db path to point to the db instead of the dir
  - [x]     backward compatible - if to dir, use it (warning!), if to file, use it
  - [x]     update docs
- [x] if have db arg
  - [x]     create table if not exist
- [x] remove dummy client from docker image
- [x] add flask
  - [x]     bulma css?
  - [x]     do not start webui if db arg is missing (error)
  - [x]     add/remove requirements from requirements.txt
  - [x]     update docs
  - [x]         port 8080?
  - [x]         add screenshots! -> readme?
- [x] docker
  - [x]     new tag? or replace the old?
  - [x]     change logging to also log to stdout by default
- [x] update install instructions
  - [x]     use requirements.txt from full docker
- [x] changelog! new tag and release?
- [x] extend web interface
  - [x]     embed version info (commit time/hash)
  - [x]     show known products -> allow click to see them all (with keys!)

image

### CODE REVIEW

**Comment by Matthew-Beckett** [comment]
This is a chonker, will review ASAP.

**Review by Matthew-Beckett — APPROVED** [review]
LGTM!

**Comment by simonmicro** [comment]
@Matthew-Beckett Off - that's a good question... How do we handle betas? Shall we introduce a new tag and branch for that first?

**Comment by simonmicro** [comment]
Let's go beta!

**Pull request merged**
