### PR TITLE
Added warning about removal of Etrigan support

### PR DESCRIPTION
**Pull request by simonmicro**
This PR adds a warning about pending removal of Etrigan support.

### Why?
- Because Etrigan was not updated anymore since years - it works, but there is nobody to fix it if it breaks, so let's remove it now before it is too late.
- The Etrigan GUI is just some tkinter window. There is no real reason, why to limit it to Etrigan-only existence!
- Dropping GUI support will remove some boilerplate code from the client
- Dropping GUI code will remove MUCH code from the server + some libraries
- It gives us/me the ability to focus on developing a new web-based GUI, while the old is being stripped out at the same moment -> that will then solve the issue #75 

### Remaining steps
- [ ] Test on real hardware (both bare+Docker), just in case I made a typo :P

### CODE REVIEW

**Comment by Matthew-Beckett** [comment]
image

We are looking, we are looking 👀

**Comment by simonmicro** [comment]
@Matthew-Beckett Thanks - you are blazing-fast! I'll have to test it at least once to be sure, but I don't think I'll need to fix anything after that :grin:

**Comment by Matthew-Beckett** [comment]
> @Matthew-Beckett Thanks - you are blazing-fast! I'll have to test it at least once to be sure, but I don't think I'll need to fix anything after that :grin: 

I agree, deprecation warnings are unlikely to break other stuff.

**Comment by simonmicro** [comment]
Without 964dde625eb4f232b50fb2860b35905c923ec985 the warning is now shown (at least when starting from the console anyways)...

**Comment by simonmicro** [comment]
Just for documentation - this is the current Etrigan GUI...

Screenshot from 2022-12-07 13-21-51
Screenshot from 2022-12-07 13-23-48

**Comment by Matthew-Beckett** [comment]
> Just for documentation - this is the current Etrigan GUI...
> 
> 
> 
> Screenshot from 2022-12-07 13-21-51
> 
> Screenshot from 2022-12-07 13-23-48
> 
> 

I don't think this a great loss... Looks like a WindowsPE Point of Sale system.

**Comment by simonmicro** [comment]
Well, I did not want to be disrespectful, but I'm sure now that we have to kill it - before it reproduces! :laughing:

**Pull request merged**
